import time
a=input('Digite algo ')
print('Qual é o tipo primitivo ?')
time.sleep (1.5)
print(type(a))
time.sleep (1.5)
print('É numerico ?')
time.sleep(1.5)
print(a.isnumeric())
time.sleep (1.5)
print('Esta em caixa alta ?')
time.sleep(1.5)
print(a.isupper())
time.sleep (1.5)
print('Esta em caixa baixa ?')
time.sleep (1.5)
print(a.islower())
time.sleep (1.5)
print('É somente espaço ?')
time.sleep (1.5)
print(a.isspace())
time.sleep (1.5)
print('É printavel ?')
time.sleep (1.5)
print(a.isprintable())
time.sleep (1.5)
print('É alfabético ?')
time.sleep (1.5)
print(a.isalpha())
time.sleep (1.5)
print('Pronto, você ja sabe tudo sobre oque digitou')
time.sleep (2)
print('Até mais')
time.sleep (3)